"""Added payment table

Revision ID: 1fa3ca53dd3e
Revises: c8d330501777
Create Date: 2025-05-29 01:29:43.513619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fa3ca53dd3e'
down_revision: Union[str, None] = 'c8d330501777'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stop', sa.Boolean(), nullable=False),
    sa.Column('use_count', sa.Integer(), nullable=False),
    sa.Column('data_name', sa.String(length=720), nullable=True),
    sa.Column('data_one', sa.String(length=720), nullable=True),
    sa.Column('data_two', sa.String(length=720), nullable=True),
    sa.Column('data_three', sa.String(length=720), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment')
    # ### end Alembic commands ###