"""Add data_photo to user

Revision ID: 325a7f45586d
Revises: 1fa3ca53dd3e
Create Date: 2025-06-23 17:36:00.336439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '325a7f45586d'
down_revision: Union[str, None] = '1fa3ca53dd3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('data_photo', sa.LargeBinary(), nullable=True))
    op.add_column('user', sa.Column('data_photo', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###
    # pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'data_photo')
    op.drop_column('payment', 'data_photo')
    # ### end Alembic commands ###
    # pass
