"""Changes payment info len

Revision ID: 685dd5acd0cb
Revises: ee8b0f5489d8
Create Date: 2025-03-24 22:09:03.753973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '685dd5acd0cb'
down_revision: Union[str, None] = 'ee8b0f5489d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payment', 'data_one',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=35),
               type_=sa.String(length=720),
               existing_nullable=True)
    op.alter_column('payment', 'data_two',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=35),
               type_=sa.String(length=720),
               existing_nullable=True)
    op.alter_column('payment', 'data_three',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=35),
               type_=sa.String(length=720),
               existing_nullable=True)
    op.alter_column('user', 'data_one',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=35),
               type_=sa.String(length=720),
               existing_nullable=True)
    op.alter_column('user', 'data_two',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=35),
               type_=sa.String(length=720),
               existing_nullable=True)
    op.alter_column('user', 'data_three',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=35),
               type_=sa.String(length=720),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'data_three',
               existing_type=sa.String(length=720),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=35),
               existing_nullable=True)
    op.alter_column('user', 'data_two',
               existing_type=sa.String(length=720),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=35),
               existing_nullable=True)
    op.alter_column('user', 'data_one',
               existing_type=sa.String(length=720),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=35),
               existing_nullable=True)
    op.alter_column('payment', 'data_three',
               existing_type=sa.String(length=720),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=35),
               existing_nullable=True)
    op.alter_column('payment', 'data_two',
               existing_type=sa.String(length=720),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=35),
               existing_nullable=True)
    op.alter_column('payment', 'data_one',
               existing_type=sa.String(length=720),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=35),
               existing_nullable=True)
    # ### end Alembic commands ###