"""Delete payment table

Revision ID: 82a678224478
Revises: 685dd5acd0cb
Create Date: 2025-04-20 13:30:57.790277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '82a678224478'
down_revision = '685dd5acd0cb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('stop', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('use_count', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('data_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=720), nullable=True),
    sa.Column('data_one', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=720), nullable=True),
    sa.Column('data_two', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=720), nullable=True),
    sa.Column('data_three', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=720), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###