"""Delete status

Revision ID: abfdfa6e4d07
Revises: 82a678224478
Create Date: 2025-04-29 20:53:47.304222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'abfdfa6e4d07'
down_revision: Union[str, None] = '82a678224478'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'status_list')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('status_list', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=False))
    # ### end Alembic commands ###