"""Add data_photo to user

Revision ID: ccd98f8bd73d
Revises: 325a7f45586d
Create Date: 2025-06-23 17:48:53.185075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccd98f8bd73d'
down_revision: Union[str, None] = '325a7f45586d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('attachment_path', sa.String(length=720), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'attachment_path')
    # ### end Alembic commands ###