"""Added initial table

Revision ID: ee8b0f5489d8
Revises: 
Create Date: 2025-02-09 23:10:57.040570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee8b0f5489d8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stop', sa.Boolean(), nullable=False),
    sa.Column('use_count', sa.Integer(), nullable=False),
    sa.Column('data_name', sa.String(length=720), nullable=True),
    sa.Column('data_one', sa.String(length=35), nullable=True),
    sa.Column('data_two', sa.String(length=35), nullable=True),
    sa.Column('data_three', sa.String(length=35), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram', sa.BigInteger(), nullable=False),
    sa.Column('message_counter', sa.Integer(), nullable=False),
    sa.Column('global_message_counter', sa.Integer(), nullable=False),
    sa.Column('status_list', sa.Text(), nullable=False),
    sa.Column('stop', sa.Boolean(), nullable=False),
    sa.Column('data_name', sa.String(length=720), nullable=True),
    sa.Column('data_one', sa.String(length=35), nullable=True),
    sa.Column('data_two', sa.String(length=35), nullable=True),
    sa.Column('data_three', sa.String(length=35), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('from_me', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    op.drop_table('user')
    op.drop_table('payment')
    # ### end Alembic commands ###